#!/usr/bin/env bash
# Installation and basic nginx configuration

# Installation and getting running
apt-get update
apt-get install nginx -y
ufw enable -y
ufw allow 'Nginx HTTP' -y

# Configure to serve Hello World
echo "Hello World!" > /var/www/html/index.nginx-debian.html