#!/usr/bin/env bash
# Installation and basic nginx configuration

apt-get update
apt-get install nginx -y

sudo chown -R "$USER":"$USER" /var/www/html/
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

echo "Hello World!" > /var/www/html/index.html

sed -i '/listen 80 default_server;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default 
sudo service nginx restart

service nginx restart
