#!/usr/bin/env bash
# Installation and basic nginx configuration

#!/usr/bin/env bash
# Installation and basic nginx configuration

apt purge --autoremove nginx -y

apt install curl gnupg2 ca-certificates lsb-release ubuntu-keyring -y

curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
    | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" \
    | sudo tee /etc/apt/sources.list.d/nginx.list

echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
    | sudo tee /etc/apt/preferences.d/99nginx

apt update -y
apt install nginx -y

echo "Hello World!" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html


sed -i 's/#error_page/error_page/' /etc/nginx/conf.d/default.conf
sed -i '/error_page.*404.*404.html/a \\n    location /redirect_me {\n        return 301 https://www.youtube.com;\n    }' /etc/nginx/conf.d/default.conf
sed -i '/error_page.*404.*404.html/a \\n    add_header X-Served-By $hostname;' /etc/nginx/conf.d/default.conf

service nginx start


