#!/usr/bin/env bash
# This script creates a file and ends up deleting it

file=/var/run/myscript.pid

#Displays I hate the kill command when receiving a SIGTERM signal
trap 'echo "I hate the kill command"; sudo rm $file; exit' SIGTERM

#Displays Y U no love me?! when receiving a SIGINT signal
trap 'echo Y U no love me?!; exit' SIGINT

#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap 'rm $file; exit' SIGQUIT

#Creates the file /var/run/myscript.pid containing its PID
touch $file
echo $$ > $file

#Displays To infinity and beyond indefinitely
while true
do
	echo "To infinity and beyond"
	sleep 2
done

