#!/usr/bin/env bash
# Managed the manage_my_process script

file='/var/run/my_process.pid'

func_start()
{
	./manage_my_process &
	touch $file
	echo $! > $file
}

func_stop()
{
	kill "$(cat $file)"
	rm $file
}


case $1 in
	'start')
		func_start
		echo 'manage_my_process started'
	;;
	'stop')
		func_stop
		echo 'manage_my_process stopped'
	;;
	'restart')
		func_stop
		func_start
		echo 'manage_my_process restarted'
	;;
	*)
	echo 'Usage: manage_my_process {start|stop|restart}'
	;;
esac
