#!/usr/bin/env bash
# This program ignores the SIGTERM command
 
# Set a trap for SIGINT and SIGTERM signals
trap "echo I am invisible!!!" SIGTERM
 
while true
do
  echo "To infinity and beyond"
  sleep 2
done
