#!/usr/bin/env bash
#configure an Ubuntu server hosts

cp /etc/hosts ~/hosts.bak

sed -i 's/^[0-9].*localhost$/127.0.0.2'$'\tlocalhost/' ~/hosts.bak
echo -e "\n8.8.8.8	facebook.com" >> ~/hosts.bak

cp -f ~/hosts.bak /etc/hosts
